///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace ERP218_integration
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The click recording.
    /// </summary>
    [TestModule("a323eba0-21da-451d-91bb-15cc6603d4e6", ModuleType.Recording, 1)]
    public partial class click : ITestModule
    {
        /// <summary>
        /// Holds an instance of the ERP218_integrationRepository repository.
        /// </summary>
        public static ERP218_integrationRepository repo = ERP218_integrationRepository.Instance;

        static click instance = new click();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public click()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static click Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Move item 'SaisieFactureClient.Monecran.Barre_boutons_1.BoutonCREER' at Center.", repo.SaisieFactureClient.Monecran.Barre_boutons_1.BoutonCREERInfo, new RecordItemIndex(0));
            repo.SaisieFactureClient.Monecran.Barre_boutons_1.BoutonCREER.MoveTo();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SaisieFactureClient.Monecran.Barre_boutons_1.BoutonCREER' at Center.", repo.SaisieFactureClient.Monecran.Barre_boutons_1.BoutonCREERInfo, new RecordItemIndex(1));
            repo.SaisieFactureClient.Monecran.Barre_boutons_1.BoutonCREER.Click();
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
