///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace ERP218_integration
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the ERP218_integrationRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("c01a887e-ce44-4fed-818c-c1779686fd3c")]
    public partial class ERP218_integrationRepository : RepoGenBaseFolder
    {
        static ERP218_integrationRepository instance = new ERP218_integrationRepository();

        /// <summary>
        /// Gets the singleton class instance representing the ERP218_integrationRepository element repository.
        /// </summary>
        [RepositoryFolder("c01a887e-ce44-4fed-818c-c1779686fd3c")]
        public static ERP218_integrationRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public ERP218_integrationRepository() 
            : base("ERP218_integrationRepository", "/", null, 0, false, "c01a887e-ce44-4fed-818c-c1779686fd3c", ".\\RepositoryImages\\ERP218_integrationRepositoryc01a887e.rximgres")
        {
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("c01a887e-ce44-4fed-818c-c1779686fd3c")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class ERP218_integrationRepositoryFolders
    {
    }
#pragma warning restore 0436
}
